version: "3.8" # Version 3.8 is quite new and should work

services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: ./frontend/dev.Dockerfile
    volumes:
      - ./frontend/:/usr/src/app
    ports:
      - 3001:3000
    container_name: frontend-dev
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  backend:
    image: backend
    build:
      context: .
      dockerfile: ./backend/dev.Dockerfile
    volumes:
      - ./backend/:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    container_name: backend-dev

volumes:
  mongo_data:
