POST http://localhost:3000/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InFxcSIsImlkIjoiNjNjM2E2ODgyZjM4ODUxYWVkMzZiMGE5IiwiaWF0IjoxNjczNzY4Nzk1LCJleHAiOjE2NzM3NzIzOTV9.XE0OMK21je8Hrwz1fYgfPqcgCCo-XzTijdwpJ6ErlpI

{
    "title": "goo3gl3e2224",
    "author": "G323224",
    "url": "www3.googl324e.fi",
    "likes": 111
}