version: "3.8" # Version 3.8 is quite new and should work

services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3000
    container_name: frontend-dev
